"""Methodology, design choices, and explicit limitations."""

from __future__ import annotations

from pathlib import Path

import streamlit as st

PROJECT_ROOT = Path(__file__).parent.parent.parent.resolve()
OUT = PROJECT_ROOT / "output"

st.set_page_config(page_title="Methodology", page_icon="📐", layout="wide")
st.title("Methodology")

st.markdown(
    """
This dashboard summarises a **portfolio-level** short-term load forecasting
system for ~16,500 Spanish residential households (GoiEner dataset).

## Core methodological commitments

- **Walk-forward validation, not random k-fold.** Random k-fold leaks
  future information into the past in a time-series setting. Every
  metric on the Validation page comes from rolling-window walk-forward
  with strict time ordering.

- **Probabilistic forecasts with calibration.** Five LightGBM quantile
  models (q05 / q25 / q50 / q75 / q95) per (level, horizon). Pinball
  loss and coverage rates are reported alongside the headline MAPE — a
  4% MAPE is meaningless if the 90% interval covers only 50% of
  realized values.

- **Persistence baseline reported with every metric.** Reading "MAPE
  4%" only makes sense in the context of the no-model benchmark: if
  persistence is at 4.5% the gap is small; if it's at 8% the model is
  doing real work.

- **Hierarchical reconciliation across behavioral segments.** Households
  cluster into 4 archetypes by their pre-2020 daily load shape. Forecasts
  are produced at portfolio + each segment, then reconciled with
  bottom-up and MinT-OLS so the parts sum to the whole.

- **Champion / challenger promotion with structured logging.** A new
  model is promoted only if it improves MAPE by at least 0.2 percentage
  points without degrading calibration.

## Design choices worth knowing

- **Direct-h LightGBM at horizons 24h and 168h.** The supervised target
  is `kwh_total.shift(-h)`. Evaluation produces one prediction point per
  fold per horizon. Extending to a richer horizon grid is straightforward
  (extend `HORIZONS_H`) but multiplies model count linearly.

- **Realized weather, not forecast weather.** This likely overstates
  performance vs a true production setting. A real deployment would
  consume an AEMET / ENTSO-E forecast feed at issue time and propagate
  the additional uncertainty.

- **Portfolio-level, not production-level.** Runs offline on a laptop.
  No FastAPI endpoint, no Airflow DAG, no MLflow registry. The
  productionization layer is straightforward infrastructure that any
  team adds in a week.

## Out of scope by design

- Deep learning (LSTM, TFT) — the marginal gain over a tuned LightGBM
  on this data scale rarely justifies the complexity.
- Causal effect estimation — out of scope; this pipeline forecasts
  demand, it does not estimate household-level responses to tariff
  or policy changes.
- Real-time inference — see "portfolio-level, not production-level"
  above.

## Known approximations in this build

- The configured `NOMINAL_INTERVALS` lists 80% and 95% intervals, but
  `QUANTILES` does not include the 0.025 / 0.10 / 0.90 / 0.975 points
  required to evaluate them natively. Coverage on this dashboard is
  reported at the **50% interval (q25, q75)** and **90% interval
  (q05, q95)** — the natively trained intervals. Adding finer
  quantiles is a config change.

- **Sample-mode walk-forward** uses a 28-day step (vs 7 in spec) to
  keep the run under five minutes. SARIMAX is fit on the last 90 days
  per fold instead of the full 365. Both relaxations apply only when
  `GOIENER_DATA_MODE=sample`.

## Where each artefact comes from

| Artefact | Generated by |
|---|---|
| Headline metrics | `code/10_summarize_results.py` (reads `06_metrics_summary.csv`) |
| Walk-forward results | `code/06_walk_forward_validation.py` |
| Segments / centroids | `code/02_segment_households.py` |
| Reconciled forecasts | `code/07_hierarchical_reconcile.py` |
| Daily batch forecasts | `code/08_run_daily_batch.py` |
| Promotion decisions | `code/09_evaluate_challenger.py` |
"""
)

narr_path = OUT / "10_results_narrative.md"
econ_path = OUT / "10_economic_interpretation.md"
if narr_path.exists():
    with st.expander("Auto-generated results narrative"):
        st.markdown(narr_path.read_text(encoding="utf-8"))
if econ_path.exists():
    with st.expander("Economic interpretation of feature importance"):
        st.markdown(econ_path.read_text(encoding="utf-8"))
